### ISSUE TITLE
Collisions with other extensions

### ISSUE THREAD

**Issue by uberkael** [pedrohenrique-ql/vscode-regex-match#95]
Hello, thank for this great extension.

It seems like there is some collision with another extension (TODO Tree) that uses regex for coloring text in the document:
![image](https://github.com/user-attachments/assets/26318754-ba38-44b6-833a-ea9f93893cc5)

```
[error] SyntaxError: Invalid flags: dg
    at k (/home/user/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:114:74341)
    at Array.d (/home/user/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:114:3580)
    at Object.parse (/home/user/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:114:71938)
    at Object.r.parse (/home/user/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:1:12754)
    at Object.parse (/home/user/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:114:415)
    at l (/home/user/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:52:165)
    at Array.get [as indices] (/home/user/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:52:2895)
    at RegexTest.processMatch (/home/user/.vscode/extensions/pedrohenrique-ql.regex-match-0.4.2/src/RegexTest.ts:87:15)
    at RegexTest.test (/home/user/.vscode/extensions/pedrohenrique-ql.regex-match-0.4.2/src/RegexTest.ts:42:37)
    at /home/user/.vscode/extensions/pedrohenrique-ql.regex-match-0.4.2/src/decorations/TextDecorationApplier.ts:19:72
    at Array.flatMap (<anonymous>)
    at Function.updateDecorations (/home/user/.vscode/extensions/pedrohenrique-ql.regex-match-0.4.2/src/decorations/TextDecorationApplier.ts:19:39)
    at RegexMatchService.updateRegexTest (/home/user/.vscode/extensions/pedrohenrique-ql.regex-match-0.4.2/src/RegexMatchService.ts:85:27)
    at RegexMatchService.openRegexTestWindow (/home/user/.vscode/extensions/pedrohenrique-ql.regex-match-0.4.2/src/RegexMatchService.ts:80:10)
    at d.h (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:206473) regex-match.openRegexMatchWindow {"value":"pedrohenrique-ql.regex-match","_lower":"pedrohenrique-ql.regex-match"}
```

Even if is not the extension fault, maybe this error can highlight unwanted interactions or leaking in the code.

Thanks!

**Comment by uberkael** [comment]
Probably related:

https://github.com/Gruntfuggly/todo-tree/issues/853

**Comment by pedrohenrique-ql** [comment]
Hi, @uberkael! Thanks for the report and the acknowledgements, I still plan to make many improvements!

Regarding the issue, from what I saw in the issue https://github.com/Gruntfuggly/todo-tree/issues/853, the TODO Tree extension replaces the RegExp object globally and does not accept the `/d` flag, which is valid (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions#regex_flags). This flag is essential for Regex Match to get the indexes of the matches. 

I will comment on the issue as other developers have done, as I believe it is not a good practice to replace something like this.

Thanks!

**Comment by uberkael** [comment]
Yes, it seems that TODO Tree is to blame.

Thank for the extension.
